### ISSUE TITLE
问一个关于Kumo的小问题(

### ISSUE THREAD

**Issue by kagg886** [MisakaTAT/Yuri-Kotlin#149]
这是报错
![6b7fed938602bd156253df1c78b0c236](https://github.com/user-attachments/assets/bbd3736f-571f-445e-8bbc-f1f140f048d0)

这是代码
![096f4b30c95faa1b5ab5b398a60378c2](https://github.com/user-attachments/assets/dada8806-c4b9-4531-9bff-861db89f8f96)

这是字体
![image](https://github.com/user-attachments/assets/887233f7-d620-4a3b-8d38-d1b391c3d3a1)

有趣的是，无论我在WSL下测试，还是在远程上测试均不会报错
但是触发自家bot命令后会词云生成阶段就会爆这个错误，真不知道为什么。。。

**Comment by MisakaTAT** [comment]
可能是数据中有空字符串，检查下看看？或者 TrimSpace 下。

**Comment by kagg886** [comment]
> 可能是数据中有空字符串，检查下看看？或者 TrimSpace 下。

经过确认，所有的数据都没有空字符串。

以下是remote debug的一些发现：

1. kumo内部会依赖stringWidth方法取字符串在特定font下的长度

![Image_1730341592741.png](https://github.com/user-attachments/assets/507d37e5-df05-4a92-bd71-0cfe194d3017)

2. 程序实际上会走到handleCharWidth

![Image_1730341597030.png](https://github.com/user-attachments/assets/b2817b61-fd3b-462d-9302-18fa14f9c171)

3. 最终调用unsafe对象从native中取值，这个值就是一个char的宽度，令人惊讶的是只有在打包后使用bot命令触发后，这个值才是0，否则均不为0。

![Image_1730341646185.png](https://github.com/user-attachments/assets/d84b6e12-d93b-40b6-a050-b6a9d74063d8)


所以对于这种情况大佬有什么思路吗，反正我黔驴技穷了(((

**Comment by MisakaTAT** [comment]
你jdk版本多少？打包后无论是bot指令触发还是代码里直接触发都会出现吗？

**Comment by kagg886** [comment]
用openjdk

17和21均出现这个问题

将出问题的数据dump下来，

在wsl中跑测试
在出问题的环境中编译测试都没有问题
唯独打生产包时，bot触发命令时，会有这个问题

**Comment by MisakaTAT** [comment]
那这个有点奇怪了，有检查过打包后的 font 和 background img有被正常加载吗？

**Comment by kagg886** [comment]
> 那这个有点奇怪了，有检查过打包后的 font 和 background img有被正常加载吗？

一定被加载了吧，毕竟如果没加载就不是这个错误了x

**Comment by MisakaTAT** [comment]
> > 那这个有点奇怪了，有检查过打包后的 font 和 background img有被正常加载吗？
> 
> 一定被加载了吧，毕竟如果没加载就不是这个错误了x

主要是只有打包后出现这个问题，就感觉比较奇怪（

**Comment by xiaomujin** [comment]
换个字体试过嘛

**Comment by kagg886** [comment]
> 换个字体试过嘛

试过的！我resource里的字体都试了

(默认的字体不支持中文所以没用默认的)
